### ISSUE TITLE
提个过滤抓取意见

### ISSUE THREAD

**Issue by hyx52077** [liesauer/TeleMediaSpider#1]
可以过滤视频文件大小或者过滤视频秒数就好了

**Comment by liesauer** [comment]
这个做的时候也有考虑过，但是我个人偏向于后期二次筛选处理，因为能保留原数据，后面怎么过滤都没问题。

但是爬虫这边直接过滤了，以后你又想抓回来，那只能重新改配置，重新抓一遍。

可以考虑加过滤功能，但个人还是不建议在爬虫这边直接过滤。

**Comment by hyx52077** [comment]
感谢回复，因为我这个频道基本上低于 20M的视频 ，大于100M基本是广告  ，你懂的

**Comment by liesauer** [comment]
已添加文件大小过滤功能，配置参考：[文件大小过滤](https://github.com/liesauer/TeleMediaSpider?tab=readme-ov-file#5-%E5%A4%A7%E5%B0%8F%E8%BF%87%E6%BB%A4)
