### ISSUE TITLE
接收不到验证码

### ISSUE THREAD

**Issue by MagneticLine** [liesauer/TeleMediaSpider#11]
![image](https://github.com/user-attachments/assets/1a3fb6b8-df80-4d0d-918f-9dfcc58e22b4)
使用了可以接受tg短信验证码的手机号也不行

**Comment by liesauer** [comment]
在其他已经登陆的TG客户端会收到官方信息，不需要手机短信。

**Comment by liesauer** [comment]
如果你这个号从没在别的客户端登陆过，那就没办法了，这是tg的问题。

**Comment by MagneticLine** [comment]
> 在其他已经登陆的TG客户端会收到官方信息，不需要手机短信。

在其他客户端登陆过的，但是没有收到验证码消息

**Comment by liesauer** [comment]
手机号要完整，含区域号，比如中国就是+86xxxxxxxx

**Comment by MagneticLine** [comment]
> 手机号要完整，含区域号，比如中国就是+86xxxxxxxx

是的，是完整的

**Comment by liesauer** [comment]
那就不清楚了

**Comment by liesauer** [comment]
现在还是这样吗？试下创建app时，将平台改成别的试下。

**Comment by MagneticLine** [comment]
> 现在还是这样吗？试下创建app时，将平台改成别的试下。

现在还是这样，而且似乎tg的api应用无法注销再重新创建，当时创建的时候选择的是其他平台。等我有新的账号了再试试

**Comment by liesauer** [comment]
可能有用的相关信息：https://www.v2ex.com/t/1099185
