### ISSUE TITLE
How to get apiId and apiHash?

### ISSUE THREAD

**Issue by sonake** [liesauer/TeleMediaSpider#3]

**Comment by liesauer** [comment]
follow this document, [Getting API ID and API HASH](https://gram.js.org/getting-started/authorization#getting-api-id-and-api-hash).

**Comment by sonake** [comment]
> follow this document, [Getting API ID and API HASH](https://gram.js.org/getting-started/authorization#getting-api-id-and-api-hash).

<img width="924" alt="image" src="https://github.com/user-attachments/assets/2320a88d-a512-4e91-85f9-1c70e31a040f">

**Comment by liesauer** [comment]
尝试更换别的梯子节点，或者参考这个issue提到的一些解决方法，[Telegram API Development says "error"](https://github.com/tdlib/telegram-bot-api/issues/273)，我当初也是换了节点才成功的。

**Comment by liesauer** [comment]
这个视频也可以参考下，https://www.youtube.com/watch?v=BV_UYI9G4hM

**Comment by sonake** [comment]
main」任务过程中发生错误：
RPCError: 400: PHONE_NUMBER_INVALID (caused by auth.SendCode)

**Comment by liesauer** [comment]
> main」任务过程中发生错误： RPCError: 400: PHONE_NUMBER_INVALID (caused by auth.SendCode)

需要加上区域号，比如大陆手机号就是：+86xxxxxxxxxx，其他区域同理

**Comment by sonake** [comment]
> > main」任务过程中发生错误： RPCError: 400: PHONE_NUMBER_INVALID (caused by auth.SendCode)
> 
> 需要加上区域号，比如大陆手机号就是：+86xxxxxxxxxx，其他区域同理

请问在哪里加手机号呢

**Comment by liesauer** [comment]
文档有说哦
![image](https://github.com/user-attachments/assets/94524ce1-6eca-41e8-b7c4-100fa4878539)


对应文件内容
![image](https://github.com/user-attachments/assets/6970cd7b-7c91-44ab-81a2-3e90e417673f)

**Comment by sonake** [comment]
能不能获取文本内容呢，普通消息，消息好像不是实时的，需要改动什么呢

**Comment by sonake** [comment]
如果我想拿到消息的第一时间转发，应该在哪里修改呢

**Comment by liesauer** [comment]
这个爬虫不抓取文本消息的，抓取保存的相关逻辑在这里

https://github.com/liesauer/TeleMediaSpider/blob/e2acc8b5286b5e3ca2593f55dc4897ee00c347d8/src/index.ts#L306-L497

**Comment by liesauer** [comment]
> 如果我想拿到消息的第一时间转发，应该在哪里修改呢

消息转发的api可以参考：https://gram.js.org/tl/messages/ForwardMessages#messagesforwardmessages

**Comment by sonake** [comment]
好的谢谢

**Comment by sonake** [comment]
我稍微改动了下代码，请问怎么打包成linux的执行文件，让其运行在服务器上呢

**Comment by liesauer** [comment]
> 我稍微改动了下代码，请问怎么打包成linux的执行文件，让其运行在服务器上呢

使用vscode打开项目，并运行`pack executable`任务，文件编译在`output`文件夹下

**Comment by sonake** [comment]
命令行直接执行么，不好意思，vscode用的不是很熟练

**Comment by liesauer** [comment]
> 命令行直接执行么，不好意思，vscode用的不是很熟练

不是，vscode里`Ctrl + Shift + T`

**Comment by sonake** [comment]
谢谢

**Comment by sonake** [comment]
<img width="707" alt="image" src="https://github.com/user-attachments/assets/92977e6a-915f-466a-a01f-cfcd3208df6c">
请问这个应该怎么处理呢

**Comment by liesauer** [comment]
> <img alt="image" width="707" src="https://private-user-images.githubusercontent.com/46209482/372896365-92977e6a-915f-466a-a01f-cfcd3208df6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NTM4OTAsIm5iZiI6MTcyODU1MzU5MCwicGF0aCI6Ii80NjIwOTQ4Mi8zNzI4OTYzNjUtOTI5NzdlNmEtOTE1Zi00NjZhLWEwMWYtY2ZjZDMyMDhkZjZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDA5NDYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1MzI4NzRkZDY4MmNiZjAwZjdlY2VhZjY2MDVlZjZmMzRmZjc0YTkxYmE1ZjhhODEzNWY0ZjM1M2U4OTNhZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZJJ1ncvD6tsKegbYdASDE281YRFn4IFz4H9N8UiawUQ"> 请问这个应该怎么处理呢

你用的node是什么版本的？

**Comment by sonake** [comment]
> > <img alt="image" width="707" src="https://private-user-images.githubusercontent.com/46209482/372896365-92977e6a-915f-466a-a01f-cfcd3208df6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NTM4OTAsIm5iZiI6MTcyODU1MzU5MCwicGF0aCI6Ii80NjIwOTQ4Mi8zNzI4OTYzNjUtOTI5NzdlNmEtOTE1Zi00NjZhLWEwMWYtY2ZjZDMyMDhkZjZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDA5NDYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1MzI4NzRkZDY4MmNiZjAwZjdlY2VhZjY2MDVlZjZmMzRmZjc0YTkxYmE1ZjhhODEzNWY0ZjM1M2U4OTNhZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZJJ1ncvD6tsKegbYdASDE281YRFn4IFz4H9N8UiawUQ"> 请问这个应该怎么处理呢
> 
> 你用的node是什么版本的？

v22.9.0

**Comment by liesauer** [comment]
你是有改过什么东西嘛？加了macos的target？具体改了哪些内容

**Comment by sonake** [comment]
> 你是有改过什么东西嘛？加了macos的target？具体改了哪些内容

我是在获取频道消息的时候只筛选了文字，文字图片做了合成，配置方面没有动过，使用了jimp这个工具包

**Comment by liesauer** [comment]
你这个跑的命令怎么和写的不一样，多了`-t`参数

![image](https://github.com/user-attachments/assets/2ccee121-628e-449d-aedc-2de322dac590)

![image](https://github.com/user-attachments/assets/5e67439a-002e-493c-bd63-412f62acaacc)

**Comment by sonake** [comment]
<img width="531" alt="image" src="https://github.com/user-attachments/assets/101ed48c-04ba-4c5a-808d-2d1d8c9a180e">
<img width="722" alt="image" src="https://github.com/user-attachments/assets/e489f88b-109c-406e-9670-8ca6aa2de470">
参数配置是没有的

**Comment by liesauer** [comment]
你还有别的系统或者机器吗，看下会不会也报这个

**Comment by liesauer** [comment]
> 你还有别的系统或者机器吗，看下会不会也报这个

我在wsl上也复现了，但由于使用的依赖 [vercel/pkg](https://github.com/vercel/pkg) 已经处于非维护状态，所以已经无法提issue了

几个相关的issue：
https://github.com/vercel/pkg/issues/1131
https://github.com/vercel/pkg/issues/2022

**Comment by liesauer** [comment]
已经找到问题了，是由于`*`在linux终端被解析了，将打包命令改成这样就可以了
```
                "pkg",
                "--no-bytecode",
                "--public-packages",
                "\"*\"",
                "--public",
                "--compress",
                "GZip",
                "${workspaceFolder}/package.json",
                "-o",
                "${workspaceFolder}/output/TeleMediaSpider"
```

**Comment by sonake** [comment]
> 已经找到问题了，是由于`*`在linux终端被解析了，将打包命令改成这样就可以了
> 
> ```
>                 "pkg",
>                 "--no-bytecode",
>                 "--public-packages",
>                 "\"*\"",
>                 "--public",
>                 "--compress",
>                 "GZip",
>                 "${workspaceFolder}/package.json",
>                 "-o",
>                 "${workspaceFolder}/output/TeleMediaSpider"
> ```

辛苦啊，我试试呢

**Comment by sonake** [comment]
> > 已经找到问题了，是由于`*`在linux终端被解析了，将打包命令改成这样就可以了
> > ```
> >                 "pkg",
> >                 "--no-bytecode",
> >                 "--public-packages",
> >                 "\"*\"",
> >                 "--public",
> >                 "--compress",
> >                 "GZip",
> >                 "${workspaceFolder}/package.json",
> >                 "-o",
> >                 "${workspaceFolder}/output/TeleMediaSpider"
> > ```
> 
> 辛苦啊，我试试呢

顺便有个小case，macos系统不支持打包win，只支持linux的

**Comment by liesauer** [comment]
> 顺便有个小case，macos系统不支持打包win，只支持linux的

这个估计无解了，[vercel/pkg](https://github.com/vercel/pkg) 都已经不维护了

根据这个issue，https://github.com/vercel/pkg/issues/1277 ，TeleMediaSpider默认应该打包的是x64吧，也是打包失败？你截图看下

**Comment by sonake** [comment]
> > 顺便有个小case，macos系统不支持打包win，只支持linux的
> 
> 这个估计无解了，[vercel/pkg](https://github.com/vercel/pkg) 都已经不维护了
> 
> 根据这个issue，[vercel/pkg#1277](https://github.com/vercel/pkg/issues/1277) ，TeleMediaSpider默认应该打包的是x64吧，也是打包失败？你截图看下
大概是"can not bulid win"之类的

**Comment by sonake** [comment]
打包成功了，如何执行呢
![image](https://github.com/user-attachments/assets/be3b1b9d-5f74-48a3-96d5-bd10653d31bc)
如果我的服务器就是国外的，代理的配置应该就不用了吧

**Comment by liesauer** [comment]
能访问tg服务器就不需要

**Comment by sonake** [comment]
> 能访问tg服务器就不需要

linux怎么启动呢

**Comment by liesauer** [comment]
> 打包成功了，如何执行呢 ![image](https://private-user-images.githubusercontent.com/46209482/378270532-be3b1b9d-5f74-48a3-96d5-bd10653d31bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0OTE3NjMsIm5iZiI6MTcyOTQ5MTQ2MywicGF0aCI6Ii80NjIwOTQ4Mi8zNzgyNzA1MzItYmUzYjFiOWQtNWY3NC00OGEzLTk2ZDUtYmQxMDY1M2QzMWJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDA2MTc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMDUxZWQ0NjYxZTVlM2VjYjk2OTY3MDA5MDdmZjk2OWMxZDM0ZjczMDQ1NDc4ODUwZDQ1OTlkNTU3MTNkZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4arQf2XGU9jt8NHCgAna8ztRkn3fNmjrhad_jTeSG0E) 如果我的服务器就是国外的，代理的配置应该就不用了吧

你这是在macos打包，在linux上运行吗，这看起来打包出来的程序是坏的

**Comment by sonake** [comment]
> > 打包成功了，如何执行呢 ![image](https://private-user-images.githubusercontent.com/46209482/378270532-be3b1b9d-5f74-48a3-96d5-bd10653d31bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0OTE3NjMsIm5iZiI6MTcyOTQ5MTQ2MywicGF0aCI6Ii80NjIwOTQ4Mi8zNzgyNzA1MzItYmUzYjFiOWQtNWY3NC00OGEzLTk2ZDUtYmQxMDY1M2QzMWJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDA2MTc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMDUxZWQ0NjYxZTVlM2VjYjk2OTY3MDA5MDdmZjk2OWMxZDM0ZjczMDQ1NDc4ODUwZDQ1OTlkNTU3MTNkZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4arQf2XGU9jt8NHCgAna8ztRkn3fNmjrhad_jTeSG0E) 如果我的服务器就是国外的，代理的配置应该就不用了吧
> 
> 你这是在macos打包，在linux上运行吗，这看起来打包出来的程序是坏的

![image](https://github.com/user-attachments/assets/cd43833f-6af3-4e77-9601-e36bcee194d7)
又打了一次，打完我想在macos先试试

**Comment by liesauer** [comment]
那你要加一个macos的target喔，https://github.com/vercel/pkg?tab=readme-ov-file#targets

改这个地方就行了，加一个`node18-macos-x64`
https://github.com/liesauer/TeleMediaSpider/blob/3dc101e7ddf23823bc61d0b6e18a6337a43f01ae/package.json#L12-L15

**Comment by sonake** [comment]
> 那你要加一个macos的target喔，https://github.com/vercel/pkg?tab=readme-ov-file#targets
> 
> 改这个地方就行了，加一个`node18-macos-x64`
> 
> https://github.com/liesauer/TeleMediaSpider/blob/3dc101e7ddf23823bc61d0b6e18a6337a43f01ae/package.json#L12-L15

ok ,我试试

**Comment by liesauer** [comment]
另外我不确定是不是默认arch识别之类的问题，试下将`node18-win`改成`node18-win-x64`，`node18-linux`改成`node18-linux-x64`，看下windows和linux能跑吗

**Comment by sonake** [comment]
![image](https://github.com/user-attachments/assets/0f6c5f96-e662-4c09-97ea-d07efbe3e717)
怎么执行呢，需要安装么

**Comment by liesauer** [comment]
并不需要安装，这是因为打包出来的程序是坏的，提示已经说明了，`cannot execute binary file: Exec format error`，你有windows机器吗，我实测windows下打包，windows版和linux版都是能正常跑的

**Comment by sonake** [comment]
win倒是有一台，但是没环境，您是使用win进行打包的么

**Comment by liesauer** [comment]
> win倒是有一台，但是没环境，您是使用win进行打包的么

对，装个node环境就行

**Comment by sonake** [comment]
> > win倒是有一台，但是没环境，您是使用win进行打包的么
> 
> 对，装个node环境就行

行，我晚上试试

**Comment by sonake** [comment]
> > > win倒是有一台，但是没环境，您是使用win进行打包的么
> > 
> > 
> > 对，装个node环境就行
> 
> 行，我晚上试试

打包没问题，但是服务器运行可执行文件有个报错，可能是我引包的方式有问题，麻烦帮我看下
<img width="1039" alt="image" src="https://github.com/user-attachments/assets/7c48a927-d8c8-4693-96b4-69ab185d4a2c">
![2061731523734_ pic](https://github.com/user-attachments/assets/37871270-5af3-4690-8926-730163b9686f)

**Comment by liesauer** [comment]
如果依赖的包用了动态加载之类的技术，pkg可能分析不出来依赖链，需要自行添加文件进去

https://github.com/liesauer/TeleMediaSpider/blob/3dc101e7ddf23823bc61d0b6e18a6337a43f01ae/package.json#L9-L11

**Comment by sonake** [comment]
> 如果依赖的包用了动态加载之类的技术，pkg可能分析不出来依赖链，需要自行添加文件进去
> 
> https://github.com/liesauer/TeleMediaSpider/blob/3dc101e7ddf23823bc61d0b6e18a6337a43f01ae/package.json#L9-L11

![image](https://github.com/user-attachments/assets/4a1bdf07-5b5f-4519-a92a-8f5bc307f4ff)
这样添加呗

**Comment by liesauer** [comment]
名字要完全对应，不是看包名的，提示是什么路径就填什么，还有如果要打包所有文件（包括子文件夹里面的），要写`**/*`，

![image](https://github.com/user-attachments/assets/135499cc-08ac-423d-a326-e7003341fadc)

**Comment by sonake** [comment]
<img width="805" alt="image" src="https://github.com/user-attachments/assets/70ea1d80-3469-4995-aaf8-75c92410f755">
这个请问要修改什么
