### ISSUE TITLE
RPCError: 400: CHANNEL_PRIVATE (caused by channels.GetChannels)

### ISSUE THREAD

**Issue by sonake** [liesauer/TeleMediaSpider#6]
![image](https://github.com/user-attachments/assets/8a55b44e-af3d-479d-97fd-2191cc5bd073)
这个请问需要修改哪里

**Comment by liesauer** [comment]
这个暂时没有办法代码上解决，相关issue：https://github.com/gram-js/gramjs/issues/742

不过你可以手机上TG，把每一个群都点一遍，然后会有一些群提示private什么的，确定，把回话消掉，全部点完，再运行，应该就好了

**Comment by sonake** [comment]
> 这个暂时没有办法代码上解决，相关issue：[gram-js/gramjs#742](https://github.com/gram-js/gramjs/issues/742)
> 
> 不过你可以手机上TG，把每一个群都点一遍，然后会有一些群提示private什么的，确定，把回话消掉，全部点完，再运行，应该就好了

一定会有这种群提示么，我翻了一圈没找见

**Comment by liesauer** [comment]
应该会有这个提示的，你那边全部都点一遍，爬虫获取的时候还是在报错吗

![image](https://github.com/user-attachments/assets/2415941f-af1f-478c-8819-d6c20200a9a1)

**Comment by sonake** [comment]
> 应该会有这个提示的，你那边全部都点一遍，爬虫获取的时候还是在报错吗
> 
> ![image](https://private-user-images.githubusercontent.com/8676741/386221436-2415941f-af1f-478c-8819-d6c20200a9a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1OTMzNTAsIm5iZiI6MTczMTU5MzA1MCwicGF0aCI6Ii84Njc2NzQxLzM4NjIyMTQzNi0yNDE1OTQxZi1hZjFmLTQ3OGMtODgxOS1kNmMyMDIwMGE5YTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTRUMTQwNDEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGVmNzZiMDFkOGQ3ODFkZTM3Yjg1NWIwZjgyNWRiNzU3MTU2MGEzZWI2Y2NkNzBhMDZiNDcyYTkxYmVkNjdhNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.hewSnvyYji1lgANbZpuq-Gsf2hhttv_zSWzti2jxON0)

我基本都点了，就是最近加了一个需要申请的群，也不是频道

**Comment by sonake** [comment]
> > 应该会有这个提示的，你那边全部都点一遍，爬虫获取的时候还是在报错吗
> > ![image](https://private-user-images.githubusercontent.com/8676741/386221436-2415941f-af1f-478c-8819-d6c20200a9a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1OTMzNTAsIm5iZiI6MTczMTU5MzA1MCwicGF0aCI6Ii84Njc2NzQxLzM4NjIyMTQzNi0yNDE1OTQxZi1hZjFmLTQ3OGMtODgxOS1kNmMyMDIwMGE5YTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTRUMTQwNDEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGVmNzZiMDFkOGQ3ODFkZTM3Yjg1NWIwZjgyNWRiNzU3MTU2MGEzZWI2Y2NkNzBhMDZiNDcyYTkxYmVkNjdhNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.hewSnvyYji1lgANbZpuq-Gsf2hhttv_zSWzti2jxON0)
> 
> 我基本都点了，就是最近加了一个需要申请的群，也不是频道

找到了，我再试试

**Comment by sonake** [comment]
> > > 应该会有这个提示的，你那边全部都点一遍，爬虫获取的时候还是在报错吗
> > > ![image](https://private-user-images.githubusercontent.com/8676741/386221436-2415941f-af1f-478c-8819-d6c20200a9a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1OTMzNTAsIm5iZiI6MTczMTU5MzA1MCwicGF0aCI6Ii84Njc2NzQxLzM4NjIyMTQzNi0yNDE1OTQxZi1hZjFmLTQ3OGMtODgxOS1kNmMyMDIwMGE5YTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTRUMTQwNDEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGVmNzZiMDFkOGQ3ODFkZTM3Yjg1NWIwZjgyNWRiNzU3MTU2MGEzZWI2Y2NkNzBhMDZiNDcyYTkxYmVkNjdhNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.hewSnvyYji1lgANbZpuq-Gsf2hhttv_zSWzti2jxON0)
> > 
> > 
> > 我基本都点了，就是最近加了一个需要申请的群，也不是频道
> 
> 找到了，我再试试

找到一个点了，但是启动还是这个错误

**Comment by liesauer** [comment]
还有一个办法代码解决，这里改成循环一个一个获取，然后使用promise catch，如果报private的异常，就跳过这个频道，留下好的

https://github.com/liesauer/TeleMediaSpider/blob/3dc101e7ddf23823bc61d0b6e18a6337a43f01ae/src/index.ts#L89-L91

**Comment by sonake** [comment]
> 还有一个办法代码解决，这里改成循环一个一个获取，然后使用promise catch，如果报private的异常，就跳过这个频道，留下好的
> 
> https://github.com/liesauer/TeleMediaSpider/blob/3dc101e7ddf23823bc61d0b6e18a6337a43f01ae/src/index.ts#L89-L91

嗯，我再试试

**Comment by sonake** [comment]
<img width="664" alt="image" src="https://github.com/user-attachments/assets/e7c488a2-b293-4cab-b1e7-78eee6ca21a3">
<img width="360" alt="image" src="https://github.com/user-attachments/assets/ab86aa7e-fd7c-4ef9-9bd0-7b64ab06199a">

这个是哪里配置错了么

**Comment by liesauer** [comment]
你是不是改了这个？这个不能乱改的，把这行删了

![image](https://github.com/user-attachments/assets/5493b26d-1ed2-4baa-9931-4841a056b42b)

**Comment by sonake** [comment]
能设置后台运行么

**Comment by liesauer** [comment]
你可以使用nohup等工具来实现后台运行，还有不确定是tg问题还是什么问题，我这边windows运行，在运行几个小时后会出现采集完全不动的情况，建议写个脚本每隔1-2小时重启爬虫，由于支持断点续爬，所以可以放心强杀重启

**Comment by sonake** [comment]
ok

**Comment by sonake** [comment]
![image](https://github.com/user-attachments/assets/a47dc52c-020c-4e77-b1fc-f116ccea72e3)
请问这种是正常的么

**Comment by liesauer** [comment]
> 请问这种是正常的么

正常的，库有自动重连功能的

**Comment by sonake** [comment]
> > 请问这种是正常的么
> 
> 正常的，库有自动重连功能的

请问如何获取图片的http链接，因为我需要转发下消息

**Comment by liesauer** [comment]
不存在直链，你要转发消息可用api转发，https://gram.js.org/tl/messages/ForwardMessages#messagesforwardmessages

**Comment by sonake** [comment]
> 不存在直链，你要转发消息可用api转发，https://gram.js.org/tl/messages/ForwardMessages#messagesforwardmessages

主要想往微信转发，看起来方便

**Comment by sonake** [comment]
> 你可以使用nohup等工具来实现后台运行，还有不确定是tg问题还是什么问题，我这边windows运行，在运行几个小时后会出现采集完全不动的情况，建议写个脚本每隔1-2小时重启爬虫，由于支持断点续爬，所以可以放心强杀重启

linux也存在，做了1小时的重启，谢谢
